database:
  url: "mariadb+pymysql://kong:12345678%40Abc@10.0.6.86:3306/test_yen"

app:
  version: "1.0.0"
  secret_key: "nhyen"
  host: "0.0.0.0"
  port: 5000

log:
  version: 1
  objects:
    queue:
      class: queue.Queue
      maxsize: 10000

  formatters:
    simple:
      format: '%(asctime)s-%(name)s-%(levelname)s-%(message)s'
    simple_color:
      class: colorlog.ColoredFormatter
      format: '%(log_color)s-%(asctime)s-%(name)s-%(levelname)s-%(message)s'

  handlers:
    elk:
      class: cow.logging_.ELKHandler
      level: INFO
      app_id: scrpy
      system_id: collab

    console:
      class: colorlog.StreamHandler
      level: DEBUG
      formatter: simple_color
      stream: ext://sys.stdout

    file:
      class: logging.handlers.RotatingFileHandler
      filename: '/tmp/log.log'
      formatter: simple
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

    queue_listener:
      class: cow.logging_.QueueListenerHandler
      respect_handler_level: true
      handlers:
        - cfg://handlers.console
        - cfg://handlers.file
      #        - cfg://handlers.elk
      queue: cfg://objects.queue

  loggers:
    disable_log: &disable
      level: ERROR
      handlers:
        - queue_listener
      propagate: false

    werkzeug:
      <<: *disable
    chardet:
      <<: *disable
    urllib3:
      <<: *disable
    selenium.webdriver.remote.remote_connection:
      <<: *disable

    info:
      level: INFO
      handlers:
        - queue_listener
      propagate: false

    __main__:
      level: DEBUG
      handlers:
        - queue_listener
      propagate: false
    root:
      level: DEBUG
      handlers:
        - console
        - file
        - queue_listener
      propogate: true